### PR TITLE
Use new Python 2.6/3.x compatible exception syntax

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Review by jamadden — COMMENTED** [review]
Thanks! That looks good to me, and it’s a simple enough standalone change that I don’t think it needs extra tests or changes to CI. There aren’t even any existing classifiers to worry about, though a note in CHANGES.txt might be nice. 

It was once the policy of this organization that any substantial changes that could be considered copyrighted only be accepted from someone who had signed the contributor agreement. Simple changes could bypass that check. Signing the agreement would confer membership in the organization and members can (were expected to, after approval) merge their own PRs. IANAL, but this change would seem to be simple enough to bypass the requirement for membership. 

However, I suspect that there are new governance structures in place with the subsuming of the Zope foundation by the Plone foundation, and I don’t know what the rules are. Perhaps someone who does can comment? I used to ask @tseaver about this.

**Comment by stevepiercy** [comment]
I will push another commit for a note in CHANGES.txt.

FTR, I have no problem signing an agreement under Zope, and I have signed the Plone Contributor Agreement. Please let me know if you need me to sign something.

**Comment by stevepiercy** [comment]
Commit to CHANGES.txt pushed.

**Comment by ableeb** [comment]
@stevepiercy the Zope contributor agreement explained here: 
https://community.plone.org/t/becoming-a-contributor-updated-version/8550. Technically, you should sign it before any contribution is accepted. That said, Plone enforces this with a 'bot, which I don't think is set up for Zope.

**Comment by stevepiercy** [comment]
@ableeb Sent!

**Comment by stevepiercy** [comment]
Invitation to zopefoundation accepted.

What's the next step? Do I merge this PR myself or someone else?

How does a release get made? I'm eager to test it out in a deployment via Ansible and the Plone server playbook.

**Review by jugmac00 — APPROVED** [review]
Looks good to me

**Comment by jugmac00** [comment]
Concerning the merge - @jamadden worte:

>  Signing the agreement would confer membership in the organization and members can (were expected to, after approval) merge their own PRs.

So, basically you need the agreement signed (check), and you need a positive review (approval) from another Zope contributor (check), then you can and should merge yourself.

**Comment by jugmac00** [comment]
Concerning the packaging process... 

Having a look at https://pypi.org/project/zc.monitor/ ... hm, I am not sure who of them is still active.

Pinging @jimfulton @benji-york @freddrake @garyposter 

Maybe you could give @mgedmin @jamadden @icemac or @dataflake access to this PyPi package?

Thank you!

**Comment by benji-york** [comment]
Thanks for the ping; I've given @mgedmin and @dataflake Owner access to the PyPI repo.

**Comment by stevepiercy** [comment]
@mgedmin or @dataflake would you please cut a release for this merged PR? I'd like to test it out this US holiday weekend. Thank you!

**Comment by dataflake** [comment]
I have no idea why I am listed as maintainer on PyPI, I have nothing to do with this package. I'll defer to @mgedmin

**Comment by icemac** [comment]
@mgedmin As this change is not yet released, I'd like to volunteer to make this release but I (`icemac`) would need PyPI rights to do so.

**Comment by benji-york** [comment]
> [...] but I (`icemac`) would need PyPI rights to do so.

Done!

**Comment by icemac** [comment]
I just released https://pypi.org/project/zc.monitor/0.4.0.post1/.
I do not have much hope that it runs on Python 3 as it needs `zc.ngi` which is currently Python-2-only.

**Comment by icemac** [comment]
For details see #3.

**Comment by mgedmin** [comment]
(Sorry, I was AFK for a couple of weeks for life reasons.)

**Pull request merged**
